name: update_data

on:
  schedule:
    - cron: '00 01 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install pandas plotly html5lib beautifulsoup4 requests dash

    - name: Ejecutar script de datos
      run: python app.py

    - name: Hacer commit y push a GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@://github.com'
        git add *.csv index.html data.json grafico_animado.json
        # Solo sube si hay datos verdaderamente nuevos para evitar errores
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatizado: Actualización diaria de métricas" && git push)